points:
  - id: 1
    x: 11.027094
    y: 0.977534
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "stand"
  - id: 2
    x: 11.290615
    y: 0.978596
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "_wall"
  - id: 3
    x: 12.166615
    y: 0.982478
    fast: true
    constant_speed: false
    segment_custom_speed: true
    segment_speed_level: 1
    segment_linear_x: 0.300000
    segment_max_angular_speed: 1.800000
    segment_k_alpha: 2.400000
    segment_k_beta: -0.600000
    task_type: none
    event_label: ""
  - id: 4
    x: 12.485122
    y: 0.988609
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 5
    x: 12.751538
    y: 0.993054
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 6
    x: 12.848211
    y: 0.992255
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 7
    x: 12.924911
    y: 1.013827
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 8
    x: 12.991181
    y: 1.078777
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 9
    x: 13.236686
    y: 1.544421
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 10
    x: 13.243053
    y: 1.586038
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 11
    x: 13.235219
    y: 1.625196
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 12
    x: 13.179433
    y: 1.808210
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 13
    x: 13.122244
    y: 2.271685
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 14
    x: 13.115168
    y: 3.523615
    fast: false
    constant_speed: false
    segment_custom_speed: true
    segment_speed_level: 3
    segment_linear_x: 0.600000
    segment_max_angular_speed: 1.800000
    segment_k_alpha: 2.400000
    segment_k_beta: -0.600000
    task_type: none
    event_label: ""
