points:
  - id: 1
    x: 10.665347
    y: 1.937882
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "@stop_2"
  - id: 2
    x: 10.670319
    y: 2.783082
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
