points:
  - id: 1
    x: 2.657778
    y: 1.119722
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 2
    x: 1.105264
    y: 0.987436
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 3
    x: 0.975242
    y: 1.026443
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 4
    x: 0.884226
    y: 1.143463
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 5
    x: 0.945327
    y: 1.277808
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 6
    x: 1.022693
    y: 1.371971
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 7
    x: 1.018708
    y: 1.506690
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 8
    x: 1.021966
    y: 4.953156
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 9
    x: 1.034785
    y: 5.048012
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 10
    x: 1.104003
    y: 5.145431
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 11
    x: 1.234750
    y: 5.160813
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 12
    x: 1.361143
    y: 5.124010
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 13
    x: 1.478707
    y: 5.009152
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 14
    x: 1.691792
    y: 4.997532
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "bridge"
  - id: 15
    x: 2.514603
    y: 4.999750
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 16
    x: 4.410870
    y: 4.994027
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "stand"
  - id: 17
    x: 4.489793
    y: 4.992590
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 18
    x: 4.621715
    y: 4.944771
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 19
    x: 4.685983
    y: 4.798932
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 20
    x: 4.716848
    y: 4.160323
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 21
    x: 4.735234
    y: 4.070694
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 22
    x: 4.815475
    y: 3.989369
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 23
    x: 5.858966
    y: 4.026595
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 24
    x: 5.947230
    y: 4.065823
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 25
    x: 6.380364
    y: 4.817839
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 26
    x: 6.532384
    y: 4.941920
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 27
    x: 6.735423
    y: 4.988794
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 28
    x: 9.355029
    y: 4.939379
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "low"
  - id: 29
    x: 10.639765
    y: 4.945499
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
