points:
  - id: 1
    x: 11.027094
    y: 5.022466
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "stand"
  - id: 2
    x: 11.290615
    y: 5.021404
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "_wall"
  - id: 3
    x: 12.166615
    y: 5.017522
    fast: true
    constant_speed: false
    segment_custom_speed: true
    segment_speed_level: 1
    segment_linear_x: 0.300000
    segment_max_angular_speed: 1.800000
    segment_k_alpha: 2.400000
    segment_k_beta: -0.600000
    task_type: none
    event_label: ""
  - id: 4
    x: 12.485122
    y: 5.011391
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 5
    x: 12.751538
    y: 5.006946
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 6
    x: 12.848211
    y: 5.007745
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 7
    x: 12.924911
    y: 4.986173
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 8
    x: 12.991181
    y: 4.921223
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 9
    x: 13.236686
    y: 4.455579
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 10
    x: 13.243053
    y: 4.413962
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 11
    x: 13.235219
    y: 4.374804
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 12
    x: 13.179433
    y: 4.191790
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 13
    x: 13.122244
    y: 3.728315
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 14
    x: 13.139319
    y: 2.719041
    fast: false
    constant_speed: false
    segment_custom_speed: true
    segment_speed_level: 2
    segment_linear_x: 0.450000
    segment_max_angular_speed: 1.800000
    segment_k_alpha: 2.400000
    segment_k_beta: -0.600000
    task_type: none
    event_label: "_flat"
  - id: 15
    x: 13.124017
    y: 2.642484
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 16
    x: 13.077379
    y: 2.590192
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 17
    x: 12.536090
    y: 2.429078
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 18
    x: 12.310046
    y: 2.250336
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 19
    x: 12.226003
    y: 2.045173
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 20
    x: 12.305102
    y: 1.882031
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 21
    x: 12.491726
    y: 1.724327
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 22
    x: 13.620881
    y: 1.252130
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 23
    x: 13.700475
    y: 1.135582
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 24
    x: 13.677734
    y: 1.013349
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 25
    x: 13.436111
    y: 0.635280
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 26
    x: 12.790835
    y: 0.547159
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 27
    x: 12.662917
    y: 0.584113
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 28
    x: 12.540684
    y: 0.729087
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 29
    x: 12.178708
    y: 1.621869
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 30
    x: 12.056475
    y: 1.698620
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 31
    x: 11.894445
    y: 1.755472
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 32
    x: 11.723888
    y: 1.738417
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 33
    x: 11.618711
    y: 1.692935
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 34
    x: 11.498834
    y: 1.571791
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 35
    x: 11.271286
    y: 0.592737
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 36
    x: 11.120911
    y: 0.471784
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 37
    x: 10.937846
    y: 0.435825
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 38
    x: 10.140206
    y: 1.122318
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 39
    x: 8.876560
    y: 1.086765
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "_wall"
  - id: 40
    x: 6.556909
    y: 1.086489
    fast: false
    constant_speed: false
    segment_custom_speed: true
    segment_speed_level: 2
    segment_linear_x: 0.450000
    segment_max_angular_speed: 1.800000
    segment_k_alpha: 2.400000
    segment_k_beta: -0.600000
    task_type: none
    event_label: ""
  - id: 41
    x: 6.350052
    y: 1.195852
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "_obstacle"
  - id: 42
    x: 5.366567
    y: 1.042688
    fast: false
    constant_speed: false
    segment_custom_speed: true
    segment_speed_level: 2
    segment_linear_x: 0.450000
    segment_max_angular_speed: 1.800000
    segment_k_alpha: 2.400000
    segment_k_beta: -0.600000
    task_type: none
    event_label: ""
  - id: 43
    x: 4.362815
    y: 1.208100
    fast: false
    constant_speed: false
    segment_custom_speed: true
    segment_speed_level: 2
    segment_linear_x: 0.450000
    segment_max_angular_speed: 1.800000
    segment_k_alpha: 2.400000
    segment_k_beta: -0.600000
    task_type: none
    event_label: ""
