points:
  - id: 1
    x: 1.155882
    y: 0.929774
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 2
    x: 1.233956
    y: 0.978229
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 3
    x: 1.257089
    y: 1.062087
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 4
    x: 1.216571
    y: 1.147246
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 5
    x: 1.215124
    y: 1.293389
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 6
    x: 0.951255
    y: 1.537566
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 7
    x: 0.859475
    y: 1.640819
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 8
    x: 0.809760
    y: 1.793786
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 9
    x: 0.832705
    y: 4.080650
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 10
    x: 0.859092
    y: 4.177402
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 11
    x: 0.933855
    y: 4.260961
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 12
    x: 1.114165
    y: 4.392895
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 13
    x: 1.171337
    y: 4.472056
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 14
    x: 1.144950
    y: 4.599592
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 15
    x: 1.029803
    y: 4.633567
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 16
    x: 0.922787
    y: 4.566682
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 17
    x: -0.401542
    y: 2.687206
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 18
    x: -0.521935
    y: 2.620320
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 19
    x: -0.649017
    y: 2.647074
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 20
    x: -0.722591
    y: 2.820976
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 21
    x: -0.414919
    y: 4.593436
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
