points:
  - id: 1
    x: 2.657778
    y: 1.119722
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 2
    x: 1.105264
    y: 0.987436
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 3
    x: 0.975242
    y: 1.026443
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 4
    x: 0.884226
    y: 1.143463
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 5
    x: 0.945327
    y: 1.277808
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 6
    x: 1.022693
    y: 1.371971
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 7
    x: 1.018708
    y: 1.506690
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 8
    x: 1.021966
    y: 4.953156
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 9
    x: 1.034785
    y: 5.048012
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 10
    x: 1.104003
    y: 5.145431
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 11
    x: 1.234750
    y: 5.160813
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 12
    x: 1.361143
    y: 5.124010
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 13
    x: 1.478707
    y: 5.009152
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 14
    x: 1.691792
    y: 4.997532
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "bridge"
  - id: 15
    x: 2.514603
    y: 4.999750
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 16
    x: 4.410870
    y: 4.994027
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "stand"
  - id: 17
    x: 4.489793
    y: 4.992590
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 18
    x: 4.621715
    y: 4.944771
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 19
    x: 4.685983
    y: 4.798932
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 20
    x: 4.716848
    y: 4.160323
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 21
    x: 4.735234
    y: 4.070694
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 22
    x: 4.815475
    y: 3.989369
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 23
    x: 5.858966
    y: 4.026595
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 24
    x: 5.947230
    y: 4.065823
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 25
    x: 6.380364
    y: 4.817839
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 26
    x: 6.532384
    y: 4.941920
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 27
    x: 6.735423
    y: 4.988794
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 28
    x: 9.355029
    y: 4.939379
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "low"
  - id: 29
    x: 10.876360
    y: 4.939897
    fast: true
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "stand"
  - id: 30
    x: 10.931124
    y: 4.941370
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "_obstacle"
  - id: 31
    x: 11.073811
    y: 4.930638
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 32
    x: 12.677746
    y: 4.969547
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 33
    x: 12.820414
    y: 4.947931
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 34
    x: 12.944805
    y: 2.543138
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "_flat"
  - id: 35
    x: 12.527177
    y: 2.408900
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 36
    x: 12.462544
    y: 2.026074
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 37
    x: 12.552741
    y: 1.658437
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 38
    x: 13.396147
    y: 1.540753
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 39
    x: 13.445182
    y: 1.419799
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 40
    x: 13.513832
    y: 1.266155
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 41
    x: 13.271925
    y: 0.752919
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 42
    x: 13.043093
    y: 0.576392
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 43
    x: 12.572355
    y: 0.648311
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 44
    x: 12.454670
    y: 1.396916
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 45
    x: 12.245453
    y: 1.602864
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 46
    x: 12.039505
    y: 1.704203
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 47
    x: 11.876054
    y: 1.720549
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 48
    x: 11.719141
    y: 1.664975
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 49
    x: 11.519731
    y: 1.494986
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 50
    x: 11.451082
    y: 0.890218
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 51
    x: 11.209174
    y: 0.651580
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 52
    x: 10.597868
    y: 0.674463
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 53
    x: 10.542295
    y: 1.076552
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 54
    x: 10.460569
    y: 1.138663
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 55
    x: 10.271301
    y: 1.125682
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 56
    x: 10.053257
    y: 1.121923
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 57
    x: 8.542910
    y: 1.093977
    fast: false
    constant_speed: true
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "_wall"
  - id: 58
    x: 6.792190
    y: 1.122033
    fast: false
    constant_speed: true
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 59
    x: 6.262576
    y: 1.170242
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: "_obstacle"
  - id: 60
    x: 5.961827
    y: 1.200317
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 61
    x: 5.661029
    y: 1.061937
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 62
    x: 5.323695
    y: 1.210593
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 63
    x: 4.974925
    y: 1.084807
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
