points:
  - id: 1
    x: 3.857696
    y: 4.518135
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 2
    x: 3.861136
    y: 3.605991
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 3
    x: 2.937350
    y: 4.506535
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 4
    x: 2.978447
    y: 3.581008
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 5
    x: 3.782987
    y: 5.408952
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 6
    x: 3.685212
    y: 7.071304
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 7
    x: 2.751856
    y: 7.987932
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 8
    x: 6.643527
    y: 8.171839
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 9
    x: 7.618778
    y: 6.290450
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 10
    x: 6.823321
    y: 4.653634
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 11
    x: 6.878272
    y: 3.732404
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 12
    x: 7.916376
    y: 0.773987
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 13
    x: 6.000571
    y: 0.685337
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 14
    x: 7.595639
    y: -1.247555
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 15
    x: 8.099061
    y: -2.749999
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 16
    x: 7.199430
    y: -3.703349
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 17
    x: 8.207464
    y: -4.654974
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 18
    x: 6.238582
    y: -4.699776
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 19
    x: 4.777886
    y: -4.391270
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 20
    x: 3.784546
    y: -4.428754
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 21
    x: 3.673974
    y: -2.431839
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
  - id: 22
    x: 3.554950
    y: 0.526907
    fast: false
    constant_speed: false
    segment_custom_speed: false
    segment_constant_speed: true
    segment_speed_level: 0
    segment_linear_x: 0.000000
    segment_max_angular_speed: 0.000000
    segment_k_alpha: 0.000000
    segment_k_beta: 0.000000
    task_type: none
    event_label: ""
