points:
  - id: 1
    x: 2.657778
    y: 1.119722
    fast: true
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 2
    x: 1.105264
    y: 0.987436
    fast: true
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 3
    x: 0.975242
    y: 1.026443
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 4
    x: 0.884226
    y: 1.143463
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 5
    x: 0.945327
    y: 1.277808
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 6
    x: 1.022693
    y: 1.371971
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 7
    x: 1.018708
    y: 1.506690
    fast: true
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 8
    x: 1.008557
    y: 4.829375
    fast: true
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 9
    x: 1.014242
    y: 4.937394
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 10
    x: 1.076780
    y: 5.039729
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 11
    x: 1.199013
    y: 5.090896
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 12
    x: 1.304190
    y: 5.096581
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 13
    x: 1.478707
    y: 5.009152
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 14
    x: 2.327473
    y: 4.994100
    fast: false
    constant_speed: false
    task_type: none
    event_label: "bridge"
  - id: 15
    x: 2.462459
    y: 4.995707
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 16
    x: 2.544415
    y: 4.994100
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 17
    x: 4.070764
    y: 4.994030
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 18
    x: 4.202117
    y: 4.996825
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 19
    x: 4.969247
    y: 4.996329
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 20
    x: 5.169247
    y: 4.987633
    fast: true
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 21
    x: 7.815959
    y: 4.963109
    fast: true
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 22
    x: 8.200965
    y: 4.988918
    fast: true
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 23
    x: 9.335725
    y: 4.927586
    fast: true
    constant_speed: false
    task_type: none
    event_label: "low"
  - id: 24
    x: 10.876360
    y: 4.939897
    fast: true
    constant_speed: false
    task_type: none
    event_label: "stand"
  - id: 25
    x: 10.929953
    y: 4.943593
    fast: false
    constant_speed: false
    task_type: none
    event_label: "_obstacle"
  - id: 26
    x: 12.356541
    y: 4.924594
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 27
    x: 13.008304
    y: 4.257609
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 28
    x: 12.944805
    y: 2.543138
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 29
    x: 12.527177
    y: 2.408900
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 30
    x: 12.462544
    y: 2.026074
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 31
    x: 12.552741
    y: 1.658437
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 32
    x: 13.396147
    y: 1.540753
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 33
    x: 13.445182
    y: 1.419799
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 34
    x: 13.513832
    y: 1.266155
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 35
    x: 13.271925
    y: 0.752919
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 36
    x: 13.043093
    y: 0.576392
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 37
    x: 12.572355
    y: 0.648311
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 38
    x: 12.454670
    y: 1.396916
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 39
    x: 12.245453
    y: 1.602864
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 40
    x: 12.039505
    y: 1.704203
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 41
    x: 11.876054
    y: 1.720549
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 42
    x: 11.719141
    y: 1.664975
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 43
    x: 11.519731
    y: 1.494986
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 44
    x: 11.451082
    y: 0.890218
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 45
    x: 11.209174
    y: 0.651580
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 46
    x: 10.597868
    y: 0.674463
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 47
    x: 10.542295
    y: 1.076552
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 48
    x: 10.460569
    y: 1.138663
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
  - id: 49
    x: 10.313463
    y: 1.125587
    fast: false
    constant_speed: false
    task_type: none
    event_label: ""
